const nhoFacilityNumber = 700;

const facilityNameJa = {
  100: "北海道がんセンター",
  101: "北海道医療センター",
  102: "函館病院",
  103: "旭川医療センター",
  104: "帯広病院",
  105: "八雲病院",
  106: "弘前病院",
  107: "八戸病院",
  108: "青森病院",
  109: "盛岡医療センター",
  110: "花巻病院",
  111: "岩手病院",
  112: "釜石病院",
  113: "仙台医療センター",
  114: "仙台西多賀病院",
  115: "宮城病院",
  116: "あきた病院",
  117: "山形病院",
  118: "米沢病院",
  119: "福島病院",
  120: "いわき病院",
  200: "水戸医療センター",
  201: "霞ヶ浦医療センター",
  202: "茨城東病院",
  203: "栃木医療センター",
  204: "宇都宮病院",
  205: "高崎総合医療センター",
  206: "沼田病院",
  207: "渋川医療センター",
  208: "西埼玉中央病院",
  209: "埼玉病院",
  210: "東埼玉病院",
  211: "千葉医療センター",
  212: "千葉東病院",
  213: "下総精神医療センター",
  214: "下志津病院",
  215: "東京医療センター",
  216: "災害医療センター",
  217: "東京病院",
  218: "村山医療センター",
  219: "横浜医療センター",
  220: "久里浜医療センター",
  221: "箱根病院",
  222: "相模原病院",
  223: "神奈川病院",
  224: "西新潟中央病院",
  225: "新潟病院",
  226: "さいがた医療センター",
  227: "甲府病院",
  228: "東長野病院",
  229: "まつもと医療センター",
  230: "信州上田医療センター",
  231: "小諸高原病院",
  300: "富山病院",
  301: "北陸病院",
  302: "金沢医療センター",
  303: "医王病院",
  304: "七尾病院",
  305: "石川病院",
  306: "長良医療センター",
  307: "静岡てんかん･神経医療センター",
  309: "天竜病院",
  310: "静岡医療センター",
  311: "名古屋医療センター",
  312: "東名古屋病院",
  313: "東尾張病院",
  314: "豊橋医療センター",
  315: "三重病院",
  316: "鈴鹿病院",
  317: "三重中央医療センター",
  318: "榊原病院",
  400: "敦賀医療センター",
  401: "あわら病院",
  402: "東近江総合医療センター",
  403: "紫香楽病院",
  404: "京都医療センター",
  405: "宇多野病院",
  406: "舞鶴医療センター",
  407: "南京都病院",
  408: "大阪医療センター",
  409: "近畿中央呼吸器センター",
  410: "大阪刀根山医療センター",
  411: "大阪南医療センター",
  412: "神戸医療センター",
  413: "姫路医療センター",
  414: "兵庫あおの病院",
  415: "兵庫中央病院",
  416: "奈良医療センター",
  417: "やまと精神医療センター",
  418: "南和歌山医療センター",
  419: "和歌山病院",
  500: "鳥取医療センター",
  501: "米子医療センター",
  502: "松江医療センター",
  503: "浜田医療センター",
  504: "岡山医療センター",
  505: "南岡山医療センター",
  506: "呉医療センター",
  507: "福山医療センター",
  508: "広島西医療センター",
  509: "東広島医療センター",
  510: "賀茂精神医療センター",
  511: "関門医療センター",
  512: "山口宇部医療センター",
  513: "岩国医療センター",
  514: "柳井医療センター",
  515: "東徳島医療センター",
  516: "徳島病院",
  517: "高松医療センター",
  518: "四国こどもとおとなの医療センター",
  519: "四国がんセンター",
  520: "愛媛医療センター",
  521: "高知病院",
  600: "小倉医療センター",
  601: "九州がんセンター",
  602: "九州医療センター",
  603: "福岡病院",
  604: "大牟田病院",
  605: "福岡東医療センター",
  606: "佐賀病院",
  607: "肥前精神医療センター",
  608: "東佐賀病院",
  609: "嬉野医療センター",
  610: "長崎病院",
  611: "長崎医療センター",
  612: "長崎川棚医療センター",
  613: "熊本医療センター",
  614: "熊本南病院",
  615: "菊池病院",
  616: "熊本再春医療センター",
  617: "大分医療センター",
  618: "別府医療センター",
  619: "西別府病院",
  620: "宮崎東病院",
  621: "都城医療センター",
  622: "宮崎病院",
  623: "鹿児島医療センター",
  624: "指宿医療センター",
  625: "南九州病院",
  626: "沖縄病院",
  627: "琉球病院",
  [nhoFacilityNumber]: "本部",
};

// 施設名に ` and `, ` or `, ` near `, ` same `が含まれる場合、
// ダブルクォートで括る必要がある。
// cf.https://webofscience.help.clarivate.com/en-us/Content/wos-core-collection/woscc-search-field-tags.htm
//    OG欄参照
const facilityQueries = [
  {
    OO: [
      "Nho Hokkaido canc ctr",
      "Natl Hosp Org Hokkaido canc ctr",
      "Hokkaido canc ctr",
    ],
    AD: ["Hokkaido canc ctr"],
    facilityNumber: 100,
  },
  {
    OO: [
      "Nho Hokkaido med ctr",
      "Natl Hosp Org Hokkaido med ctr",
      "Hokkaido med ctr",
    ],
    AD: ["Hokkaido med ctr"],
    facilityNumber: 101,
  },
  {
    OO: [
      "Nho Hakodate natl hosp",
      "Natl Hosp Org Hakodate natl hosp",
      "Hakodate natl hosp",
      "NHO Hakodate hosp",
      "Natl Hosp Org Hakodate hosp",
    ],
    AD: ["Hakodate hosp", "Hakodate natl hosp"],
    facilityNumber: 102,
  },
  {
    OO: [
      "Nho Asahikawa med ctr",
      "Natl Hosp Org Asahikawa med ctr",
      "Asahikawa med ctr",
    ],
    AD: ["Asahikawa med ctr"],
    facilityNumber: 103,
  },
  {
    OO: [
      "Nho Obihiro natl hosp",
      "Natl Hosp Org Obihiro natl hosp",
      "Obihiro natl hosp",
      "NHO Obihiro hosp",
      "Natl Hosp Org Obihiro hosp",
    ],
    AD: ["Obihiro natl hosp", "Obihiro hosp"],
    facilityNumber: 104,
  },
  {
    OO: [
      "Nho Yakumo natl hosp",
      "Natl Hosp Org Yakumo natl hosp",
      "Yakumo natl hosp",
      "NHO Yakumo hosp",
      "Natl Hosp Org Yakumo hosp",
    ],
    AD: ["Yakumo natl hosp", "Yakumo hosp"],
    facilityNumber: 105,
  },
  {
    OO: [
      "Nho Hirosaki natl hosp",
      "Natl Hosp Org Hirosaki natl hosp",
      "Hirosaki natl hosp",
      "NHO Hirosaki hosp",
      "Natl Hosp Org Hirosaki hosp",
    ],
    AD: ["Hirosaki natl hosp", "Hirosaki hosp"],
    facilityNumber: 106,
  },
  {
    OO: [
      "Nho Hachinohe natl hosp",
      "Natl Hosp Org Hachinohe natl hosp",
      "Hachinohe natl hosp",
      "NHO Hachinohe hosp",
      "Natl Hosp Org Hachinohe hosp",
    ],
    AD: ["Hachinohe hosp", "Hachinohe natl hosp"],
    facilityNumber: 107,
  },
  {
    OO: [
      "Nho Aomori natl hosp",
      "Natl Hosp Org Aomori natl hosp",
      "Aomori natl hosp",
      "NHO Aomori hosp",
      "Natl Hosp Org Aomori hosp",
    ],
    AD: ["Aomori hosp", "Aomori natl hosp"],
    facilityNumber: 108,
  },
  {
    OO: [
      "Nho Morioka med ctr",
      "Natl Hosp Org Morioka med ctr",
      "Morioka med ct",
    ],
    AD: ["Morioka med ct"],
    facilityNumber: 109,
  },
  {
    OO: ["Nho Hanamaki hosp", "Natl Hosp Org Hanamaki hosp", "Hanamaki hosp"],
    AD: ["Hanamaki hosp"],
    facilityNumber: 110,
  },
  {
    OO: ["Nho Iwate hosp", "Natl Hosp Org Iwate hosp", "Iwate hosp"],
    AD: ["Iwate hosp"],
    facilityNumber: 111,
  },
  {
    OO: [
      "Nho Kamaishi natl hosp",
      "Natl Hosp Org Kamaishi natl hosp",
      "Kamaishi natl hosp",
      "NHO Kamaishi hosp",
      "Natl Hosp Org Kamaishi hosp",
    ],
    AD: ["Kamaishi hosp", "Kamaishi natl hosp"],
    facilityNumber: 112,
  },
  {
    OO: ["Nho Sendai med ctr", "Natl Hosp Org Sendai med ctr", "Sendai med ct"],
    AD: ["Sendai med ct"],
    facilityNumber: 113,
  },
  {
    OO: [
      "Nho Sendai Nishitaga hosp",
      "Natl Hosp Org Sendai Nishitaga hosp",
      "Sendai Nishitaga hosp",
      "Nho Sendai-Nishitaga hosp",
      "Natl Hosp Org Sendai-Nishitaga hosp",
      "Sendai-Nishitaga hosp",
    ],
    AD: ["Sendai-Nishitaga hosp", "Sendai Nishitaga hosp"],
    facilityNumber: 114,
  },
  {
    OO: [
      "Nho Miyagi natl hosp",
      "Natl Hosp Org Miyagi natl hosp",
      "Miyagi natl hosp",
      "NHO Miyagi hosp",
      "Natl Hosp Org Miyagi hosp",
    ],
    AD: ["Miyagi hosp", "Miyagi natl hosp"],
    facilityNumber: 115,
  },
  {
    OO: [
      "Nho Akita natl hosp",
      "Natl Hosp Org Akita natl hosp",
      "Akita natl hosp",
      "NHO Akita hosp",
      "Natl Hosp Org Akita hosp",
    ],
    AD: ["Akita natl hosp", "Akita hosp"],
    facilityNumber: 116,
  },
  {
    OO: [
      "Nho Yamagata natl hosp",
      "Natl Hosp Org Yamagata natl hosp",
      "Yamagata natl hosp",
      "NHO Yamagata hosp",
      "Natl Hosp Org Yamagata hosp",
    ],
    AD: ["Yamagata natl hosp", "Yamagata hosp"],
    facilityNumber: 117,
  },
  {
    OO: [
      "Nho Yonezawa natl hosp",
      "Natl Hosp Org Yonezawa natl hosp",
      "Yonezawa natl hosp",
      "NHO Yonezawa hosp",
      "Natl Hosp Org Yonezawa hosp",
    ],
    AD: ["Yonezawa natl hosp", "Yonezawa hosp"],
    facilityNumber: 118,
  },
  {
    OO: [
      "Nho Fukushima natl hosp",
      "Natl Hosp Org Fukushima natl hosp",
      "Fukushima natl hosp",
      "NHO Fukushima hosp",
      "Natl Hosp Org Fukushima hosp",
    ],
    AD: ["Fukushima natl hosp", "Fukushima hosp"],
    facilityNumber: 119,
  },
  {
    OO: [
      "Nho Iwaki natl hosp",
      "Natl Hosp Org Iwaki natl hosp",
      "Iwaki natl hosp",
      "NHO Iwaki hosp",
      "Natl Hosp Org Iwaki hosp",
    ],
    AD: ["Iwaki natl hosp", "Iwaki hosp"],
    facilityNumber: 120,
  },
  {
    OO: ["Nho Mito med ctr", "Natl Hosp Org Mito med ctr", "Mito med ctr"],
    AD: ["Mito med ctr"],
    facilityNumber: 200,
  },
  {
    OO: [
      "Nho Kasumigaura med ctr",
      "Natl Hosp Org Kasumigaura med ctr",
      "Kasumigaura med ctr",
    ],
    AD: ["Kasumigaura med ctr"],
    facilityNumber: 201,
  },
  {
    OO: [
      "Nho Ibarakihigashi natl hosp",
      "Natl Hosp Org Ibarakihigashi natl hosp",
      "Ibarakihigashi natl hosp",
      "NHO Ibarakihigashi hosp",
      "Natl Hosp Org Ibarakihigashi hosp",
    ],
    AD: ["Ibarakihigashi natl hosp", "Ibarakihigashi hosp"],
    facilityNumber: 202,
  },
  {
    OO: [
      "Nho Tochigi med ctr",
      "Natl Hosp Org Tochigi med ctr",
      "Tochigi med ctr",
    ],
    AD: ["Tochigi med ctr"],
    facilityNumber: 203,
  },
  {
    OO: [
      "Nho Utsunomiya natl hosp",
      "Natl Hosp Org Utsunomiya natl hosp",
      "Utsunomiya natl hosp",
      "NHO Utsunomiya hosp",
      "Natl Hosp Org Utsunomiya hosp",
    ],
    AD: ["Utsunomiya natl hosp", "Utsunomiya hosp"],
    facilityNumber: 204,
  },
  {
    OO: [
      "Nho Takasaki gen med ctr",
      "Natl Hosp Org Takasaki gen med ctr",
      "Takasaki gen med ctr",
    ],
    AD: ["Takasaki gen med ctr"],
    facilityNumber: 205,
  },
  {
    OO: [
      "Nho Numata natl hosp",
      "Natl Hosp Org Numata natl hosp",
      "Numata natl hosp",
      "NHO Numata hosp",
      "Natl Hosp Org Numata hosp",
    ],
    AD: ["Numata natl hosp", "Numata hosp"],
    facilityNumber: 206,
  },
  {
    OO: [
      "Nho Shibukawa med ctr",
      "Natl Hosp Org Shibukawa med ctr",
      "Shibukawa med ct",
    ],
    AD: ["Shibukawa med ct"],
    facilityNumber: 207,
  },
  {
    OO: [
      "Nho Nishisaitama Chuo natl hosp",
      "Nishi saitama Chuo natl hosp",
      "Natl Hosp Org Nishisaitama Chuo natl hosp",
      "Nishi saitama Chuo natl hosp",
      "Nishisaitama Chuo natl hosp",
      "Nishi saitama Chuo natl hosp",
      "Nho Nishisaitama-Chuo natl hosp",
      "Natl Hosp Org Nishisaitama-Chuo natl hosp",
      "Nishisaitama-Chuo natl hosp",
      "NHO Nishisaitama-Chuo hosp",
      "Natl Hosp Org Nishisaitama-Chuo hosp",
      "NHO Nishisaitama Chuo hosp",
      "Nishi saitama Chuo hosp",
      "Natl Hosp Org Nishisaitama Chuo hosp",
      "Nishi saitama Chuo hosp",
    ],
    AD: [
      "Nishisaitama-Chuo natl hosp",
      "Nishisaitama Chuo natl hosp",
      "Nishi saitama Chuo natl hosp",
      "Nishisaitama-Chuo hosp",
      "Nishisaitama Chuo hosp",
      "Nishi saitama Chuo hosp",
    ],
    facilityNumber: 208,
  },
  {
    OO: ["Nho Saitama hosp", "Natl Hosp Org Saitama hosp", "Saitama hosp"],
    AD: ["Saitama hosp"],
    facilityNumber: 209,
  },
  {
    OO: [
      "Nho Higashisaitama natl hosp",
      "Natl Hosp Org Higashisaitama natl hosp",
      "Higashisaitama natl hosp",
      "NHO Higashisaitama hosp",
      "Natl Hosp Org Higashisaitama hosp",
    ],
    AD: ["Higashisaitama natl hosp", "Higashisaitama hosp"],
    facilityNumber: 210,
  },
  {
    OO: ["Nho Chiba med ctr", "Natl Hosp Org Chiba med ctr", "Chiba med ctr"],
    AD: ["Chiba med ctr"],
    facilityNumber: 211,
  },
  {
    OO: [
      "Nho Chibahigashi natl hosp",
      "Natl Hosp Org Chibahigashi natl hosp",
      "Chibahigashi natl hosp",
      "NHO Chibahigashi hosp",
      "Natl Hosp Org Chibahigashi hosp",
    ],
    AD: ["Chibahigashi natl hosp", "Chibahigashi hosp"],
    facilityNumber: 212,
  },
  {
    OO: [
      "Nho Shimofusa psychiat med ctr",
      "Natl Hosp Org Shimofusa psychiat med ctr",
      "Shimofusa psychiat med ct",
    ],
    AD: ["Shimofusa psychiat med ct"],
    facilityNumber: 213,
  },
  {
    OO: [
      "Nho Shimoshizu natl hosp",
      "Natl Hosp Org Shimoshizu natl hosp",
      "Shimoshizu natl hosp",
      "NHO Shimoshizu hosp",
      "Natl Hosp Org Shimoshizu hosp",
    ],
    AD: ["Shimoshizu natl hosp", "Shimoshizu hosp"],
    facilityNumber: 214,
  },
  {
    OO: ["Nho Tokyo med ctr", "Natl Hosp Org Tokyo med ctr", "Tokyo med ctr"],
    AD: ["Tokyo med ctr"],
    facilityNumber: 215,
  },
  {
    OO: [
      "Nho Disaster med ctr",
      "Natl Hosp Org Disaster med ctr",
      "Disaster med ctr",
    ],
    AD: ["Disaster med ctr"],
    facilityNumber: 216,
  },
  {
    OO: [
      "Nho Tokyo natl hosp",
      "Natl Hosp Org Tokyo natl hosp",
      "Tokyo natl hosp",
      "NHO Tokyo hosp",
      "Natl Hosp Org Tokyo hosp",
    ],
    AD: ["Tokyo hosp", "Tokyo natl hosp"],
    facilityNumber: 217,
  },
  {
    OO: [
      "Nho Murayama med ctr",
      "Natl Hosp Org Murayama med ctr",
      "Murayama med ctr",
    ],
    AD: ["Murayama med ctr"],
    facilityNumber: 218,
  },
  {
    OO: [
      "Nho Yokohama med ctr",
      "Natl Hosp Org Yokohama med ctr",
      "Yokohama med ct",
    ],
    AD: ["Yokohama med ct"],
    facilityNumber: 219,
  },
  {
    OO: [
      "Nho Kurihama Med & Addict Ctr",
      "Natl Hosp Org Kurihama Med & Addict Ctr",
      "Kurihama Med & Addict Ctr",
      'Nho Kurihama med "and" Addiction ctr',
      'Natl Hosp Org Kurihama med "and" Addiction ctr',
      'Kurihama med "and" Addiction ctr',
    ],
    AD: ['Kurihama med "and" Addiction ctr', "Kurihama Med & Addict Ctr"],
    facilityNumber: 220,
  },
  {
    OO: ["Nho Hakone hosp", "Natl Hosp Org Hakone hosp", "Hakone hosp"],
    AD: ["Hakone hosp"],
    facilityNumber: 221,
  },
  {
    OO: [
      "Nho Sagamihara natl hosp",
      "Natl Hosp Org Sagamihara natl hosp",
      "Sagamihara natl hosp",
      "NHO Sagamihara hosp",
      "Natl Hosp Org Sagamihara hosp",
    ],
    AD: ["Sagamihara hosp", "Sagamihara natl hosp"],
    facilityNumber: 222,
  },
  {
    OO: [
      "Nho Kanagawa natl hosp",
      "Natl Hosp Org Kanagawa natl hosp",
      "Kanagawa natl hosp",
      "NHO Kanagawa hosp",
      "Natl Hosp Org Kanagawa hosp",
    ],
    AD: ["Kanagawa hosp", "Kanagawa natl hosp"],
    facilityNumber: 223,
  },
  {
    OO: [
      "Nho Nishiniigata Chuo hosp",
      "Natl Hosp Org Nishiniigata Chuo hosp",
      "Nishiniigata Chuo hosp",
    ],
    AD: ["Nishiniigata Chuo hosp"],
    facilityNumber: 224,
  },
  {
    OO: [
      "Nho Niigata natl hosp",
      "Natl Hosp Org Niigata natl hosp",
      "Niigata natl hosp",
      "NHO Niigata hosp",
      "Natl Hosp Org Niigata hosp",
    ],
    AD: ["Niigata hosp", "Niigata natl hosp"],
    facilityNumber: 225,
  },
  {
    OO: [
      "Nho Saigata med ctr",
      "Natl Hosp Org Saigata med ctr",
      "Saigata med ctr",
    ],
    AD: ["Saigata med ctr"],
    facilityNumber: 226,
  },
  {
    OO: [
      "Nho Kofu natl hosp",
      "Natl Hosp Org Kofu natl hosp",
      "Kofu natl hosp",
      "NHO Kofu hosp",
      "Natl Hosp Org Kofu hosp",
    ],
    AD: ["Kofu hosp", "Kofu natl hosp"],
    facilityNumber: 227,
  },
  {
    OO: [
      "Nho Higashinagano hosp",
      "Natl Hosp Org Higashinagano hosp",
      "Higashinagano hosp",
    ],
    AD: ["Higashinagano hosp"],
    facilityNumber: 228,
  },
  {
    OO: [
      "Nho Matsumoto med ctr",
      "Natl Hosp Org Matsumoto med ctr",
      "Matsumoto med ct",
    ],
    AD: ["Matsumoto med ct"],
    facilityNumber: 229,
  },
  {
    OO: [
      "Nho Shinshu Ueda med ctr",
      "Natl Hosp Org Shinshu Ueda med ctr",
      "Shinshu Ueda med ct",
    ],
    AD: ["Shinshu Ueda med ct"],
    facilityNumber: 230,
  },
  {
    OO: [
      "Nho Komorokogen natl hosp",
      "Natl Hosp Org Komorokogen natl hosp",
      "Komorokogen natl hosp",
      "NHO Komorokogen hosp",
      "Natl Hosp Org Komorokogen hosp",
    ],
    AD: ["Komorokogen hosp", "Komorokogen natl hosp"],
    facilityNumber: 231,
  },
  {
    OO: ["Nho Toyama hosp", "Natl Hosp Org Toyama hosp", "Toyama hosp"],
    AD: ["Toyama hosp"],
    facilityNumber: 300,
  },
  {
    OO: [
      "Nho Hokuriku natl hosp",
      "Natl Hosp Org Hokuriku natl hosp",
      "Hokuriku natl hosp",
      "NHO Hokuriku hosp",
      "Natl Hosp Org Hokuriku hosp",
    ],
    AD: ["Hokuriku natl hosp", "Hokuriku hosp"],
    facilityNumber: 301,
  },
  {
    OO: [
      "Nho Kanazawa med ctr",
      "Natl Hosp Org Kanazawa med ctr",
      "Kanazawa med ctr",
    ],
    AD: ["Kanazawa med ctr"],
    facilityNumber: 302,
  },
  {
    OO: [
      "Nho Iou natl hosp",
      "Natl Hosp Org Iou natl hosp",
      "Iou natl hosp",
      "NHO Iou hosp",
      "Natl Hosp Org Iou hosp",
    ],
    AD: ["Iou hosp", "Iou natl hosp"],
    facilityNumber: 303,
  },
  {
    OO: ["Nho Nanao hosp", "Natl Hosp Org Nanao hosp", "Nanao hosp"],
    AD: ["Nanao hosp"],
    facilityNumber: 304,
  },
  {
    OO: ["Nho Ishikawa hosp", "Natl Hosp Org Ishikawa hosp", "Ishikawa hosp"],
    AD: ["Ishikawa hosp"],
    facilityNumber: 305,
  },
  {
    OO: [
      "Nho Nagara med ctr",
      "Natl Hosp Org Nagara med ctr",
      "Nagara med ctr",
    ],
    AD: ["Nagara med ctr"],
    facilityNumber: 306,
  },
  {
    OO: [
      "Nho Shizuoka Inst Neurol Disorder*",
      "Shizuoka Inst Epilepsy & Neurol Disorder*",
      "Shizuoka Inst Epilepsy",
      "Natl Hosp Org Shizuoka Inst Neurol Disorder*",
      "Shizuoka Inst Epilepsy & Neurol Disorder*",
      "Shizuoka Inst Epilepsy",
      "Shizuoka Inst Neurol Disorder*",
      "Shizuoka Inst Epilepsy & Neurol Disorder*",
      "Shizuoka Inst Epilepsy",
      'Nho Shizuoka Institute of Epilepsy "and" Neurological Disorders',
      'Natl Hosp Org Shizuoka Institute of Epilepsy "and" Neurological Disorders',
      'Shizuoka Institute of Epilepsy "and" Neurological Disorders',
    ],
    AD: [
      'Shizuoka Institute of Epilepsy "and" Neurological Disorders',
      "Shizuoka Inst Neurol Disorder*",
      "Shizuoka Inst Epilepsy & Neurol Disorder*",
      "Shizuoka Inst Epilepsy",
    ],
    facilityNumber: 307,
  },
  {
    OO: ["Nho Tenryu hosp", "Natl Hosp Org Tenryu hosp", "Tenryu hosp"],
    AD: ["Tenryu hosp"],
    facilityNumber: 309,
  },
  {
    OO: [
      "Nho Shizuoka med ctr",
      "Natl Hosp Org Shizuoka med ctr",
      "Shizuoka med ctr",
    ],
    AD: ["Shizuoka med ctr"],
    facilityNumber: 310,
  },
  {
    OO: [
      "Nho Nagoya med ctr",
      "Natl Hosp Org Nagoya med ctr",
      "Nagoya med ctr",
    ],
    AD: ["Nagoya med ctr"],
    facilityNumber: 311,
  },
  {
    OO: [
      "Nho Higashinagoya natl hosp",
      "Natl Hosp Org Higashinagoya natl hosp",
      "Higashinagoya natl hosp",
      "NHO Higashinagoya hosp",
      "Natl Hosp Org Higashinagoya hosp",
    ],
    AD: ["Higashinagoya hosp", "Higashinagoya natl hosp"],
    facilityNumber: 312,
  },
  {
    OO: [
      "Nho Higashiowari natl hosp",
      "Natl Hosp Org Higashiowari natl hosp",
      "Higashiowari natl hosp",
      "NHO Higashiowari hosp",
      "Natl Hosp Org Higashiowari hosp",
    ],
    AD: ["Higashiowari hosp", "Higashiowari natl hosp"],
    facilityNumber: 313,
  },
  {
    OO: [
      "Nho Toyohashi med ctr",
      "Natl Hosp Org Toyohashi med ctr",
      "Toyohashi med ctr",
    ],
    AD: ["Toyohashi med ctr"],
    facilityNumber: 314,
  },
  {
    OO: [
      "Nho Mie natl hosp",
      "Natl Hosp Org Mie natl hosp",
      "Mie natl hosp",
      "NHO Mie hosp",
      "Natl Hosp Org Mie hosp",
    ],
    AD: ["Mie hosp", "Mie natl hosp"],
    facilityNumber: 315,
  },
  {
    OO: [
      "Nho Suzuka natl hosp",
      "Natl Hosp Org Suzuka natl hosp",
      "Suzuka natl hosp",
      "NHO Suzuka hosp",
      "Natl Hosp Org Suzuka hosp",
    ],
    AD: ["Suzuka hosp", "Suzuka natl hosp"],
    facilityNumber: 316,
  },
  {
    OO: [
      "Nho Mie Chuo med ctr",
      "Natl Hosp Org Mie Chuo med ctr",
      "Mie Chuo med ctr",
    ],
    AD: ["Mie Chuo med ctr"],
    facilityNumber: 317,
  },
  {
    OO: [
      "Nho Sakakibara hosp",
      "Natl Hosp Org Sakakibara hosp",
      "Sakakibara hosp",
    ],
    AD: ["Sakakibara hosp"],
    facilityNumber: 318,
  },
  {
    OO: [
      "Nho Tsuruga med ctr",
      "Natl Hosp Org Tsuruga med ctr",
      "Tsuruga med ctr",
    ],
    AD: ["Tsuruga med ctr"],
    facilityNumber: 400,
  },
  {
    OO: ["Nho Awara hosp", "Natl Hosp Org Awara hosp", "Awara hosp"],
    AD: ["Awara hosp"],
    facilityNumber: 401,
  },
  {
    OO: [
      "Nho Higashi Ohmi gen med ctr",
      "Natl Hosp Org Higashi Ohmi gen med ctr",
      "Higashi Ohmi gen med ctr",
      "Nho Higashi-Ohmi gen med ctr",
      "Natl Hosp Org Higashi-Ohmi gen med ctr",
      "Higashi-Ohmi gen med ctr",
    ],
    AD: ["Higashi-Ohmi gen med ctr", "Higashi Ohmi gen med ctr"],
    facilityNumber: 402,
  },
  {
    OO: [
      "Nho Shigaraki natl hosp",
      "Natl Hosp Org Shigaraki natl hosp",
      "Shigaraki natl hosp",
      "NHO Shigaraki hosp",
      "Natl Hosp Org Shigaraki hosp",
    ],
    AD: ["Shigaraki hosp", "Shigaraki natl hosp"],
    facilityNumber: 403,
  },
  {
    OO: ["Nho Kyoto med ctr", "Natl Hosp Org Kyoto med ctr", "Kyoto med ct"],
    AD: ["Kyoto med ct"],
    facilityNumber: 404,
  },
  {
    OO: [
      "Nho Utano natl hosp",
      "Natl Hosp Org Utano natl hosp",
      "Utano natl hosp",
      "NHO Utano hosp",
      "Natl Hosp Org Utano hosp",
    ],
    AD: ["Utano hosp", "Utano natl hosp"],
    facilityNumber: 405,
  },
  {
    OO: [
      "Nho Maizuru med ctr",
      "Natl Hosp Org Maizuru med ctr",
      "Maizuru med ct",
    ],
    AD: ["Maizuru med ct"],
    facilityNumber: 406,
  },
  {
    OO: [
      "Nho Minami Kyoto hosp",
      "Natl Hosp Org Minami Kyoto hosp",
      "Minami Kyoto hosp",
    ],
    AD: ["Minami Kyoto hosp"],
    facilityNumber: 407,
  },
  {
    OO: [
      "Nho Osaka natl hosp",
      "Natl Hosp Org Osaka natl hosp",
      "Osaka natl hosp",
      "NHO Osaka hosp",
      "Natl Hosp Org Osaka hosp",
    ],
    AD: ["Osaka hosp", "Osaka natl hosp"],
    facilityNumber: 408,
  },
  {
    OO: [
      "Nho Kinki Chuo Chest med ctr",
      "Natl Hosp Org Kinki Chuo Chest med ctr",
      "Kinki Chuo Chest med ctr",
      "Nho Kinki-Chuo Chest med ctr",
      "Natl Hosp Org Kinki-Chuo Chest med ctr",
      "Kinki-Chuo Chest med ctr",
    ],
    AD: ["Kinki-Chuo Chest med ctr", "Kinki Chuo Chest med ctr"],
    facilityNumber: 409,
  },
  {
    OO: [
      "Nho Toneyama med ctr",
      "Natl Hosp Org Toneyama med ctr",
      "Toneyama med ctr",
      "Nho Osaka Toneyama med ctr",
      "Natl Hosp Org Osaka Toneyama med ctr",
      "Osaka Toneyama med ct",
    ],
    AD: ["Osaka Toneyama med ctr", "Toneyama med ctr"],
    facilityNumber: 410,
  },
  {
    OO: [
      "Nho Osaka Minami med ctr",
      "Natl Hosp Org Osaka Minami med ctr",
      "Osaka Minami med ct",
    ],
    AD: ["Osaka Minami med ct"],
    facilityNumber: 411,
  },
  {
    OO: ["Nho Kobe med ctr", "Natl Hosp Org Kobe med ctr", "Kobe med ct"],
    AD: ["Kobe med ct"],
    facilityNumber: 412,
  },
  {
    OO: ["Nho Himeji med ctr", "Natl Hosp Org Himeji med ctr", "Himeji med ct"],
    AD: ["Himeji med ct"],
    facilityNumber: 413,
  },
  {
    OO: [
      "Nho Hyogo Aono hosp",
      "Natl Hosp Org Hyogo Aono hosp",
      "Hyogo Aono hosp",
    ],
    AD: ["Hyogo Aono hosp"],
    facilityNumber: 414,
  },
  {
    OO: [
      "Nho Hyogo Chuo natl hosp",
      "Natl Hosp Org Hyogo Chuo natl hosp",
      "Hyogo Chuo natl hosp",
      "Nho Hyogo-Chuo natl hosp",
      "Natl Hosp Org Hyogo-Chuo natl hosp",
      "Hyogo-Chuo natl hosp",
      "NHO Hyogo-Chuo hosp",
      "Natl Hosp Org Hyogo-Chuo hosp",
      "NHO Hyogo Chuo hosp",
      "Natl Hosp Org Hyogo Chuo hosp",
    ],
    AD: [
      "Hyogo-Chuo natl hosp",
      "Hyogo Chuo natl hosp",
      "Hyogo-Chuo hosp",
      "Hyogo Chuo hosp",
    ],
    facilityNumber: 415,
  },
  {
    OO: ["Nho Nara med ctr", "Natl Hosp Org Nara med ctr", "Nara med ct"],
    AD: ["Nara med ct"],
    facilityNumber: 416,
  },
  {
    OO: [
      "Nho Yamato psychiat med ctr",
      "Natl Hosp Org Yamato psychiat med ctr",
      "Yamato psychiat med ctr",
    ],
    AD: ["Yamato psychiat med ctr"],
    facilityNumber: 417,
  },
  {
    OO: [
      "Nho Minami-Wakayama med ctr",
      "Natl Hosp Org Minami-Wakayama med ctr",
      "Minami-Wakayama med ctr",
      "Nho Minami Wakayama med ctr",
      "Natl Hosp Org Minami Wakayama med ctr",
      "Minami Wakayama med ctr",
    ],
    AD: ["Minami Wakayama med ctr", "Minami-Wakayama med ctr"],
    facilityNumber: 418,
  },
  {
    OO: ["Nho Wakayama hosp", "Natl Hosp Org Wakayama hosp", "Wakayama hosp"],
    AD: ["Wakayama hosp"],
    facilityNumber: 419,
  },
  {
    OO: [
      "Nho Tottori med ctr",
      "Natl Hosp Org Tottori med ctr",
      "Tottori med ctr",
    ],
    AD: ["Tottori med ctr"],
    facilityNumber: 500,
  },
  {
    OO: [
      "Nho Yonago med ctr",
      "Natl Hosp Org Yonago med ctr",
      "Yonago med ctr",
    ],
    AD: ["Yonago med ctr"],
    facilityNumber: 501,
  },
  {
    OO: [
      "Nho Matsue med ctr",
      "Natl Hosp Org Matsue med ctr",
      "Matsue med ctr",
    ],
    AD: ["Matsue med ctr"],
    facilityNumber: 502,
  },
  {
    OO: [
      "Nho Hamada med ctr",
      "Natl Hosp Org Hamada med ctr",
      "Hamada med ctr",
    ],
    AD: ["Hamada med ctr"],
    facilityNumber: 503,
  },
  {
    OO: [
      "Nho Okayama med ctr",
      "Natl Hosp Org Okayama med ctr",
      "Okayama med ctr",
    ],
    AD: ["Okayama med ctr"],
    facilityNumber: 504,
  },
  {
    OO: [
      "Nho Minami Okayama med ctr",
      "Natl Hosp Org Minami Okayama med ctr",
      "Minami Okayama med ctr",
      "Nho Minami-Okayama med ctr",
      "Natl Hosp Org Minami-Okayama med ctr",
      "Minami-Okayama med ctr",
    ],
    AD: ["Minami-Okayama med ctr", "Minami Okayama med ctr"],
    facilityNumber: 505,
  },
  {
    OO: [
      "Nho Kure med ctr",
      "Kure Med Ctr & Chugoku Canc Ctr",
      "Natl Hosp Org Kure med ctr",
      "Kure Med Ctr & Chugoku Canc Ctr",
      "Kure med ctr",
      "Kure Med Ctr & Chugoku Canc Ctr",
      'Nho Kure med ctr "and" Chugoku canc ctr',
      'Natl Hosp Org Kure med ctr "and" Chugoku canc ctr',
      'Kure med ctr "and" Chugoku canc ctr',
    ],
    AD: [
      'Kure med ctr "and" Chugoku canc ctr',
      "Kure med ctr",
      "Kure Med Ctr & Chugoku Canc Ctr",
    ],
    facilityNumber: 506,
  },
  {
    OO: [
      "Nho Fukuyama med ctr",
      "Natl Hosp Org Fukuyama med ctr",
      "Fukuyama med ctr",
    ],
    AD: ["Fukuyama med ctr"],
    facilityNumber: 507,
  },
  {
    OO: [
      "Nho Hiroshima nishi med ctr",
      "Natl Hosp Org Hiroshima nishi med ctr",
      "Hiroshima nishi med ctr",
      "Nho Hiroshimanishi med ctr",
      "Natl Hosp Org Hiroshimanishi med ctr",
      "Hiroshimanishi med ctr",
    ],
    AD: ["Hiroshimanishi med ctr", "Hiroshima nishi med ctr"],
    facilityNumber: 508,
  },
  {
    OO: [
      "Nho Higashi hiroshima med ctr",
      "Natl Hosp Org Higashi hiroshima med ctr",
      "Higashi hiroshima med ctr",
      "Nho Higashihiroshima med ctr",
      "Natl Hosp Org Higashihiroshima med ctr",
      "Higashihiroshima med ctr",
    ],
    AD: ["Higashihiroshima med ctr", "Higashi hiroshima med ctr"],
    facilityNumber: 509,
  },
  {
    OO: [
      "Nho Kamo psychiat med ctr",
      "Natl Hosp Org Kamo psychiat med ctr",
      "Kamo psychiat med ctr",
    ],
    AD: ["Kamo psychiat med ctr"],
    facilityNumber: 510,
  },
  {
    OO: [
      "Nho Kanmon med ctr",
      "Natl Hosp Org Kanmon med ctr",
      "Kanmon med ctr",
    ],
    AD: ["Kanmon med ctr"],
    facilityNumber: 511,
  },
  {
    OO: [
      "Nho Yamaguchi Ube med ctr",
      "Natl Hosp Org Yamaguchi Ube med ctr",
      "Yamaguchi Ube med ctr",
    ],
    AD: ["Yamaguchi Ube med ctr"],
    facilityNumber: 512,
  },
  {
    OO: [
      "Nho Iwakuni clin ctr",
      "Natl Hosp Org Iwakuni clin ctr",
      "Iwakuni clin ctr",
      "Nho Iwakuni Clinical ctr",
      "Natl Hosp Org Iwakuni Clinical ctr",
      "Iwakuni Clinical ctr",
    ],
    AD: ["Iwakuni Clinical ctr", "Iwakuni clin ctr"],
    facilityNumber: 513,
  },
  {
    OO: ["Nho Yanai med ctr", "Natl Hosp Org Yanai med ctr", "Yanai med ctr"],
    AD: ["Yanai med ctr"],
    facilityNumber: 514,
  },
  {
    OO: [
      "Nho Higashi tokushima med ctr",
      "Natl Hosp Org Higashi tokushima med ctr",
      "Higashi tokushima med ctr",
      "Nho Higashitokushima med ctr",
      "Natl Hosp Org Higashitokushima med ctr",
      "Higashitokushima med ctr",
    ],
    AD: ["Higashitokushima med ctr", "Higashi tokushima med ctr"],
    facilityNumber: 515,
  },
  {
    OO: [
      "Nho Tokushima natl hosp",
      "Natl Hosp Org Tokushima natl hosp",
      "Tokushima natl hosp",
      "NHO Tokushima hosp",
      "Natl Hosp Org Tokushima hosp",
    ],
    AD: ["Tokushima hosp", "Tokushima natl hosp"],
    facilityNumber: 516,
  },
  {
    OO: [
      "Nho Takamatsu med ctr",
      "Natl Hosp Org Takamatsu med ctr",
      "Takamatsu med ctr",
    ],
    AD: ["Takamatsu med ctr"],
    facilityNumber: 517,
  },
  {
    OO: [
      "Nho shikoku med ctr",
      "Shikoku Med Ctr Children & Adults",
      "Natl Hosp Org shikoku med ctr",
      "Shikoku Med Ctr Children & Adults",
      "shikoku med ctr",
      "Shikoku Med Ctr Children & Adults",
      'Nho Shikoku med ctr for Children "and" Adults',
      'Natl Hosp Org Shikoku med ctr for Children "and" Adults',
      'Shikoku med ctr for Children "and" Adults',
    ],
    AD: [
      'Shikoku med ctr for Children "and" Adults',
      "shikoku med ctr",
      "Shikoku Med Ctr Children & Adults",
    ],
    facilityNumber: 518,
  },
  {
    OO: [
      "Nho Shikoku canc ctr",
      "Natl Hosp Org Shikoku canc ctr",
      "Shikoku canc ctr",
    ],
    AD: ["Shikoku canc ctr"],
    facilityNumber: 519,
  },
  {
    OO: ["Nho Ehime med ctr", "Natl Hosp Org Ehime med ctr", "Ehime med ctr"],
    AD: ["Ehime med ctr"],
    facilityNumber: 520,
  },
  {
    OO: [
      "Nho Kochi natl hosp",
      "Natl Hosp Org Kochi natl hosp",
      "Kochi natl hosp",
      "NHO Kochi hosp",
      "Natl Hosp Org Kochi hosp",
    ],
    AD: ["Kochi hosp", "Kochi natl hosp"],
    facilityNumber: 521,
  },
  {
    OO: [
      "Nho Kokura med ctr",
      "Natl Hosp Org Kokura med ctr",
      "Kokura med ctr",
    ],
    AD: ["Kokura med ctr"],
    facilityNumber: 600,
  },
  {
    OO: [
      "Nho Kyusyu canc Ctr",
      "Natl Hosp Org Kyusyu canc Ctr",
      "Kyusyu canc Ctr",
      "Nho Kyushu canc ctr",
      "Natl Hosp Org Kyushu canc ctr",
      "Kyushu canc ct",
    ],
    AD: ["Kyushu canc ctr", "Kyusyu canc Ctr"],
    facilityNumber: 601,
  },
  {
    OO: [
      "Nho Kyusyu Med Ctr",
      "Natl Hosp Org Kyusyu Med Ctr",
      "Kyusyu Med Ctr",
      "Nho Kyushu med ctr",
      "Natl Hosp Org Kyushu med ctr",
      "Kyushu med ct",
    ],
    AD: ["Kyushu med ctr", "Kyusyu Med Ctr"],
    facilityNumber: 602,
  },
  {
    OO: [
      "Nho Fukuoka natl hosp",
      "Natl Hosp Org Fukuoka natl hosp",
      "Fukuoka natl hosp",
      "NHO Fukuoka hosp",
      "Natl Hosp Org Fukuoka hosp",
    ],
    AD: ["Fukuoka hosp", "Fukuoka natl hosp"],
    facilityNumber: 603,
  },
  {
    OO: [
      "Nho Omuta natl hosp",
      "Natl Hosp Org Omuta natl hosp",
      "Omuta natl hosp",
      "NHO Omuta hosp",
      "Natl Hosp Org Omuta hosp",
    ],
    AD: ["Omuta hosp", "Omuta natl hosp"],
    facilityNumber: 604,
  },
  {
    OO: [
      "Nho Fukuoka higashi med ctr",
      "Natl Hosp Org Fukuoka higashi med ctr",
      "Fukuoka higashi med ctr",
      "Nho Fukuokahigashi med ctr",
      "Natl Hosp Org Fukuokahigashi med ctr",
      "Fukuokahigashi med ctr",
    ],
    AD: ["Fukuokahigashi med ctr", "Fukuoka higashi med ctr"],
    facilityNumber: 605,
  },
  {
    OO: [
      "Nho Saga natl hosp",
      "Natl Hosp Org Saga natl hosp",
      "Saga natl hosp",
      "NHO Saga hosp",
      "Natl Hosp Org Saga hosp",
    ],
    AD: ["Saga hosp", "Saga natl hosp"],
    facilityNumber: 606,
  },
  {
    OO: [
      "Nho Hizen psychiat med ctr",
      "Natl Hosp Org Hizen psychiat med ctr",
      "Hizen psychiat med ctr",
    ],
    AD: ["Hizen psychiat med ctr"],
    facilityNumber: 607,
  },
  {
    OO: [
      "Nho Higashisaga natl hosp",
      "Natl Hosp Org Higashisaga natl hosp",
      "Higashisaga natl hosp",
      "NHO Higashisaga hosp",
      "Natl Hosp Org Higashisaga hosp",
    ],
    AD: ["Higashisaga hosp", "Higashisaga natl hosp"],
    facilityNumber: 608,
  },
  {
    OO: [
      "Nho Ureshino med ctr",
      "Natl Hosp Org Ureshino med ctr",
      "Ureshino med ctr",
    ],
    AD: ["Ureshino med ctr"],
    facilityNumber: 609,
  },
  {
    OO: [
      "Nho Nagasaki natl hosp",
      "Natl Hosp Org Nagasaki natl hosp",
      "Nagasaki natl hosp",
      "NHO Nagasaki hosp",
      "Natl Hosp Org Nagasaki hosp",
    ],
    AD: ["Nagasaki hosp", "Nagasaki natl hosp"],
    facilityNumber: 610,
  },
  {
    OO: [
      "Nho Nagasaki med ctr",
      "Natl Hosp Org Nagasaki med ctr",
      "Nagasaki med ctr",
    ],
    AD: ["Nagasaki med ctr"],
    facilityNumber: 611,
  },
  {
    OO: [
      "Nho Nagasaki Kawatana med ctr",
      "Natl Hosp Org Nagasaki Kawatana med ctr",
      "Nagasaki Kawatana med ctr",
    ],
    AD: ["Nagasaki Kawatana med ctr"],
    facilityNumber: 612,
  },
  {
    OO: [
      "Nho Kumamoto med ctr",
      "Natl Hosp Org Kumamoto med ctr",
      "Kumamoto med ct",
    ],
    AD: ["Kumamoto med ct"],
    facilityNumber: 613,
  },
  {
    OO: [
      "Nho Kumamotominami natl hosp",
      "Natl Hosp Org Kumamotominami natl hosp",
      "Kumamotominami natl hosp",
      "NHO Kumamotominami hosp",
      "Natl Hosp Org Kumamotominami hosp",
    ],
    AD: ["Kumamotominami hosp", "Kumamotominami natl hosp"],
    facilityNumber: 614,
  },
  {
    OO: [
      "Nho Kikuchi natl hosp",
      "Natl Hosp Org Kikuchi natl hosp",
      "Kikuchi natl hosp",
      "NHO Kikuchi hosp",
      "Natl Hosp Org Kikuchi hosp",
    ],
    AD: ["Kikuchi hosp", "Kikuchi natl hosp"],
    facilityNumber: 615,
  },
  {
    OO: [
      "Nho Kumamoto Saishun med ctr",
      "Natl Hosp Org Kumamoto Saishun med ctr",
      "Kumamoto Saishun med ctr",
    ],
    AD: ["Kumamoto Saishun med ctr"],
    facilityNumber: 616,
  },
  {
    OO: ["Nho Oita med ctr", "Natl Hosp Org Oita med ctr", "Oita med ctr"],
    AD: ["Oita med ctr"],
    facilityNumber: 617,
  },
  {
    OO: ["Nho Beppu med ctr", "Natl Hosp Org Beppu med ctr", "Beppu med ctr"],
    AD: ["Beppu med ctr"],
    facilityNumber: 618,
  },
  {
    OO: [
      "Nho Nishi beppu natl hosp",
      "Natl Hosp Org Nishi beppu natl hosp",
      "Nishi beppu natl hosp",
      "Nho Nishibeppu natl hosp",
      "Natl Hosp Org Nishibeppu natl hosp",
      "Nishibeppu natl hosp",
      "NHO Nishibeppu hosp",
      "Natl Hosp Org Nishibeppu hosp",
      "NHO Nishi beppu hosp",
      "Natl Hosp Org Nishi beppu hosp",
    ],
    AD: [
      "Nishibeppu hosp",
      "Nishi beppu hosp",
      "Nishibeppu natl hosp",
      "Nishi beppu natl hosp",
    ],
    facilityNumber: 619,
  },
  {
    OO: [
      "Nho Miyazaki Higashi hosp",
      "Natl Hosp Org Miyazaki Higashi hosp",
      "Miyazaki Higashi hosp",
    ],
    AD: ["Miyazaki Higashi hosp"],
    facilityNumber: 620,
  },
  {
    OO: [
      "Nho Miyakonojo med ctr",
      "Natl Hosp Org Miyakonojo med ctr",
      "Miyakonojo med ctr",
    ],
    AD: ["Miyakonojo med ctr"],
    facilityNumber: 621,
  },
  {
    OO: [
      "Nho Miyazaki natl hosp",
      "Natl Hosp Org Miyazaki natl hosp",
      "Miyazaki natl hosp",
      "NHO Miyazaki hosp",
      "Natl Hosp Org Miyazaki hosp",
    ],
    AD: ["Miyazaki hosp", "Miyazaki natl hosp"],
    facilityNumber: 622,
  },
  {
    OO: [
      "Nho Kagoshima med ctr",
      "Natl Hosp Org Kagoshima med ctr",
      "Kagoshima med ctr",
    ],
    AD: ["Kagoshima med ctr"],
    facilityNumber: 623,
  },
  {
    OO: [
      "Nho Ibusuki med ctr",
      "Natl Hosp Org Ibusuki med ctr",
      "Ibusuki med ctr",
    ],
    AD: ["Ibusuki med ctr"],
    facilityNumber: 624,
  },
  {
    OO: [
      "Nho Minamikyushu natl hosp",
      "Natl Hosp Org Minamikyushu natl hosp",
      "Minamikyushu natl hosp",
      "NHO Minamikyushu hosp",
      "Natl Hosp Org Minamikyushu hosp",
    ],
    AD: ["Minamikyushu hosp", "Minamikyushu natl hosp"],
    facilityNumber: 625,
  },
  {
    OO: [
      "Nho Okinawa natl hosp",
      "Natl Hosp Org Okinawa natl hosp",
      "Okinawa natl hosp",
      "NHO Okinawa hosp",
      "Natl Hosp Org Okinawa hosp",
    ],
    AD: ["Okinawa hosp", "Okinawa natl hosp"],
    facilityNumber: 626,
  },
  {
    OO: [
      "Nho Ryukyu natl hosp",
      "Natl Hosp Org Ryukyu natl hosp",
      "Ryukyu natl hosp",
      "NHO Ryukyu hosp",
      "Natl Hosp Org Ryukyu hosp",
    ],
    AD: ["Ryukyu hosp", "Ryukyu natl hosp"],
    facilityNumber: 627,
  },
  {
    OO: ["Natl Hosp Org Tokyo Headquarter", "Natl Hosp Org Headquarter"],
    AD: [
      "Natl Hosp Org Tokyo Headquarter",
      "Clin Res Ctr.*Dept Clin Data Management & Res",
    ],
    facilityNumber: nhoFacilityNumber,
  },
];
module.exports = {
  facilityQueries,
};
