function getRedCross() {
  return [
    /akita red cross hosp, /,
    /asahikawa red cross hosp, /,
    /ashikaga red cross hosp, /,
    /bomb survivors hosp, hiroshima red cross hosp & atom, /,
    /fukaya red cross hosp, /,
    /fukui red cross hosp, /,
    /fukuoka red cross hosp, /,
    /fukushima red cross hosp, /,
    /hachinohe red cross hosp, /,
    /hachinohe red cross soc hosp, /,
    /himeji red cross hosp, /,
    /hiroshima red cross blood ctr, /,
    /hiroshima red cross hosp & atom bomb survivors ho, /,
    /hiroshima red cross hosp & atom bomb survivors hos, /,
    /hiroshima red cross hosp, /,
    /hirosima red cross hosp, /,
    /ise red cross hosp, /,
    /japan red cross ise hosp, /,
    /japan red cross kitami hosp, /,
    /japan red cross maebashi hosp, /,
    /japan red cross soc himeji hosp, /,
    /japan red cross wakayama med ctr, /,
    /japan red cross yokohama city bay hosp, /,
    /kagoshima red cross hosp, /,
    /kanazawa red cross hosp, /,
    /karatsu red cross hosp, /,
    /kitami red cross hosp, /,
    /kobe red cross hosp, /,
    /kumamoto red cross hosp, /,
    /kyoto first red cross hosp, /,
    /kyoto second red cross hosp, /,
    /maebashi red cross hosp, /,
    /masuda red cross hosp, /,
    /matsuyama red cross hosp, /,
    /mihara red cross hosp, /,
    /mito red cross hosp, /,
    /musashino red cross hosp, /,
    /nagano red cross hosp, /,
    /nagaoka red cross hosp, /,
    /oita red cross hosp, /,
    /okayama red cross gen hosp, /,
    /omori red cross hosp, /,
    /osaka red cross hosp, /,
    /otsu red cross hosp, /,
    /red cross fukui hosp, /,
    /red cross tokushima hinomine rehabil ctr people d, /,
    /saitama red cross hosp, /,
    /shizuoka red cross hosp, /,
    /shobara red cross hosp, /,
    /suwa red cross hosp, /,
    /takamatsu red cross hosp, /,
    /takatsuki red cross hosp, /,
    /tokushima red cross hosp, /,
    /toyama red cross hosp, /,
    /wakayama red cross hosp, /,
    /yokohama city minato red cross hosp, /,
    /atom bomb survivors hosp/, // 広島赤十字・原爆病院
    /atom survivors hosp/,
    /survivors hosp, hiroshima, japan/,
    /japanese red cross aichi med ctr nagoya daiichi h,/,
    /japanese red cross aichi med ctr nagoya daini hos,/,
    /japanese red cross aichi med ctr nagoya first hosp, childrens med ctr,/,
    /japanese red cross aichi med ctr,/,
    /japanese red cross ashikaga hosp,/,
    /japanese red cross date hosp,/,
    /japanese red cross haramachi hosp,/,
    /japanese red cross himeji hosp,/,
    /japanese red cross hokkaido block blood ctr,/,
    /japanese red cross ise hosp,/,
    /japanese red cross ishinomaki hosp,/,
    /japanese red cross kanto koshinetsu block blood c,/,
    /japanese red cross kinki block blood ctr,/,
    /japanese red cross kitami hosp,/,
    /japanese red cross kumamoto hosp,/,
    /japanese red cross kummoto hosp,/,
    /japanese red cross kyoto daiichi hosp,/,
    /japanese red cross kyoto daini hosp,/,
    /japanese red cross kyushu block blood ctr,/,
    /japanese red cross maebashi hosp,/,
    /japanese red cross masuda hosp,/,
    /japanese red cross matsue hosp,/,
    /japanese red cross matsuyama hosp,/,
    /japanese red cross med ctr,/,
    /japanese red cross morioka hosp,/,
    /japanese red cross musashino hosp,/,
    /japanese red cross nagasaki genbaku hosp,/,
    /japanese red cross nagoya daiichi hosp,/,
    /japanese red cross nagoya daini hosp,/,
    /japanese red cross nagoya first hosp,/,
    /japanese red cross nasu hosp,/,
    /japanese red cross okayama hosp,/,
    /japanese red cross omori hosp,/,
    /japanese red cross otsu hosp,/,
    /japanese red cross sendai hosp,/,
    /japanese red cross shizuoka hosp,/,
    /japanese red cross soc himeji hosp,/,
    /japanese red cross soc suwa hosp,/,
    /japanese red cross soc,/,
    /japanese red cross takamatsu hosp,/,
    /japanese red cross takatsuki hosp,/,
    /japanese red cross tokai hokuriku block blood ctr/,
    /japanese red cross tottori hosp,/,
    /japanese red cross wakayama med ctr,/,
    /japanese red cross,/,
    /kyoto daiichi red cross hosp,/,
    /nagasaki genbaku hosp,/, // 日本赤十字社 長崎原爆病院
    /crit care ctr, maebashi, gumma 3710811, japan/, // 前橋赤十字病院
    /1-12-1,shimoteno, himeji, hyogo 6708540,/, // 姫路赤十字病院
  ];
}

module.exports = {
  getRedCross,
};
