function getSaiseikai() {
  return [
    /fukui ken saiseikai hosp,/,
    /fukui prefecture saiseikai hosp,/,
    /fukui prefecture saiseikai hosp, internal med, fukui, japan/,
    /fukuokaken saiseikai futsukaichi hosp,/,
    /gunma saiseikai maebashi & hosp,/,
    /gunma saiseikai maebashi hosp,/,
    /kumamoto saiseikai hosp, cardiovasc ctr, kumamoto, japan/,
    /mito saiseikai gen hosp,/,
    /okayama saiseikai gen hosp,/,
    /okayama saiseikai outpatient ctr hosp/, // 岡山済生会外来センター病院
    /osaka saiseikai ibaraki hosp,/,
    /osaka saiseikai nakatsu hosp,/,
    /osaka saiseikai noe hosp,/,
    /osaka saiseikai senri hosp,/,
    /saiseikai cent hosp,/,
    /saiseikai fukuoka gen hosp,/,
    /saiseikai futsukaichi hosp,/,
    /saiseikai hyogo hosp,/,
    /saiseikai hyogoken hosp,/,
    /saiseikai ibaraki hosp,/,
    /saiseikai imabari ctr hlth & welf,/,
    /saiseikai imabari hosp,/,
    /saiseikai izuo hosp,/,
    /saiseikai kagoshima hosp,/,
    /saiseikai kanazawa hosp,/,
    /saiseikai karatsu hosp,/,
    /saiseikai kawaguchi gen hosp,/,
    /saiseikai kumamoto gen hosp,/,
    /saiseikai kumamoto hosp,/,
    /saiseikai kumamoto hosp cardio vasc ctr/,
    /saiseikai kure hosp,/,
    /saiseikai kyoto hosp,/,
    /saiseikai maebashi hosp,/,
    /saiseikai matsusaka gen hosp,/,
    /saiseikai matsuyama hosp,/,
    /saiseikai matsuzaka gen hosp,/,
    /saiseikai nishiotaru hosp, otaru, hokkaido, japan/,
    /saiseikai noe hosp,/,
    /saiseikai saijo hosp,/,
    /saiseikai sendai hosp,/,
    /saiseikai senri hosp,/,
    /saiseikai shiga hosp,/,
    /saiseikai suita hosp,/,
    /saiseikai wakakusa hosp,/,
    /saiseikai yahata gen hosp,/,
    /saiseikai yamaguchi gen hosp,/,
    /saiseikai yokohama city eastern hosp,/,
    /saiseikai yokohama nanbu hosp,/,
    /saiseikai yokohama shi nanbu hosp,/,
    /saiseikai yokohama shi tobu hosp,/,
    /saiseikai yokohama tobu hosp, emergency & crit care ctr, yokohama, kanagawa, japan/,
    /saiseikai yokohamashi nanbu hosp,/,
    /saiseikai yokohamashi tobu hosp,/,
    /saiseikai yoyama hosp, toyama, japan/,
    /social welf org saiseikai imperial gift fdn inc, saiseikai kumamoto hosp, div resp med, kumamoto, japan/,
    /tokyo saiseikai cent hosp,/,
    /saiseikai narashino hosp/,
  ];
}
module.exports = {
  getSaiseikai,
};
