function getUnivNames() {
  return [
    /aichi gakuin univ, /,
    /aichi med univ hosp, /,
    /aichi med univ sch med, /,
    /aichi med univ, /,
    /akita univ hosp, /,
    /akita univ, /,
    /aoi univ hosp, /,
    /aomori univ hlth & welf, fac hlth sci, /,
    /asahi univ hosp, /,
    /asahi univ sch dent, /,
    /asahikawa med univ hosp, /,
    /asahikawa med univ, /,
    /ashikaga univ, /,
    /beppu univ, /,
    /bunkyo univ, /,
    /chiba prefecture univ hlth sci, /,
    /chiba univ hosp, /,
    /chiba univ, /,
    /chubu univ, /,
    /chuo univ, /,
    /daito bunka univ, /,
    /dokkyo med univ hosp, /,
    /dokkyo med univ koshigaya hosp, /,
    /dokkyo med univ, /,
    /doshisha univ, /,
    /ehime univ hosp, /,
    /ehime univ med sch, /,
    /ehime univ, /,
    /fkushima med univ, /,
    /fujita hlth univ hosp, /,
    /fujita hlth univ med, /,
    /fujita hlth univ orthoped surg, /,
    /fujita hlth univ, /,
    /fujita med univ, /,
    /fukuoka int univ hlth & welf/,
    /fukuoka univ chikushi hosp, /,
    /fukuoka univ hosp, /,
    /fukuoka univ, /,
    /fukushima med univ aizu med ctr, /,
    /fukushima med univ hosp, /,
    /fukushima med univ, /,
    /fukushirna med univ, /,
    /gifu kyoritsu univ, /,
    /gifu pharmaceut univ, /,
    /gifu univ grad sch med, /,
    /gifu univ hlth sci, /,
    /gifu univ hosp, /,
    /gifu univ, /,
    /gihu univ, /,
    /grad univ adv studies sokendai, /,
    /gunma univ hosp, /,
    /gunma univ, /,
    /hamamatsu univ hosp, /,
    /hamamatsu univ sch med, /,
    /hamamatsu univ, /,
    /hematol osaka city univ hosp, /,
    /hirosaki univ grad sch med, inst brain sci, /,
    /hirosaki univ hosp, /,
    /hirosaki univ, /,
    /hiroshima int univ, /,
    /hiroshima univ hosp, /,
    /hiroshima univ kasumi, /,
    /hiroshima univ, /,
    /hitotsubashi univ, /,
    /hlth sci univ hokkaido, /,
    /hokkaido informat univ, /,
    /hokkaido univ grad sch med, /,
    /hokkaido univ hosp, /,
    /hokkaido univ sci, /,
    /hokkaido univ, /,
    /hokusho univ, /,
    /hoshi univ, /,
    /hyogo med univ hosp, /,
    /hyogo med univ, /,
    /int univ hlth & welf director, clin res ctr med, ctr brain & cerebral vessels, sanno med ctr, tokyo, japan/,
    /int univ hlth & welf hosp, /,
    /int univ hlth & welf iuhw, /,
    /int univ hlth & welf mita hosp, /,
    /int univ hlth & welf narita hosp/,
    /int univ hlth & welf, /,
    /int univ hlth, welf mita hosp, /,
    /int univ hlth, welf narita hosp, /,
    /int univ hlth, welf shioya hosp, /,
    /int universityof hlth & welf, sch hlth sci fukuoka, /,
    /iryo sosei univ, /,
    /ishikawa prefectural nursing univ, /,
    /iwate med univ hosp, /,
    /iwate med univ, /,
    /jichi med univ hosp, /,
    /jichi med univ, /,
    /jikei med univ, /,
    /jikei univ daisan hosp, /,
    /jikei univ hlth care sci, /,
    /jikei univ hosp, /,
    /jikei univ kashiwa hosp, /,
    /jikei univ sch med, /,
    /jikei univ sch, /,
    /jikei univ, /,
    /jobu univ, /,
    /josai int univ, /,
    /josai univ, /,
    /junshin gakuen univ, /,
    /juntendo nerima univ hosp, /,
    /juntendo univ hosp, /,
    /juntendo univ shizuoka hosp, /,
    /juntendo univ urayasu hosp, /,
    /juntendo univ, /,
    /kagawa univ hosp, /,
    /kagawa univ, /,
    /kagoshima univ hosp, /,
    /kagoshima univ, /,
    /kanagawa dent univ, /,
    /kanagawa univ human serv, /,
    /kanazawa med univ hosp, /,
    /kanazawa med univ, /,
    /kanazawa univ hosp, /,
    /kanazawa univ sch med, /,
    /kanazawa univ, /,
    /kansai med univ hosp, /,
    /kansai med univ, /,
    /kansai univ, /,
    /kawasaki univ med welf, /,
    /keio univ hlth ctr, /,
    /keio univ hosp clin & translat res ctr ctr, /,
    /keio univ hosp, /,
    /keio univ sch med, /,
    /keio univ, /,
    /kindai univ hosp, /,
    /kindai univ nara hosp, /,
    /kindai univ sch med, /,
    /kindai univ, /,
    /kinjo gakuin univ, /,
    /kinjo univ, /,
    /kinki univ hosp, /,
    /kinki univ, /,
    /kio univ, /,
    /kitasato univ hosp, /,
    /kitasato univ med ctr, /,
    /kitasato univ, /,
    /kobe gakuin univ, /,
    /kobe pharmaceut univ, /,
    /kobe shoin womens univ, /,
    /kobe univ grad sch hlth sci, /,
    /kobe univ grad, /,
    /kobe univ hosp, /,
    /kobe univ, /,
    /kochi profess univ rehabil, /,
    /kochi univ hosp, /,
    /kochi univ technol, /,
    /kochi univ, /,
    /komatsu univ, /,
    /kumamoto hlth sci univ, /,
    /kumamoto univ hosp, /,
    /kumamoto univ, /,
    /kurume univ hosp, /,
    /kurume univ sch med, /,
    /kurume univ, /,
    /kwansei gakuin univ, /,
    /kyorin univ fac med grad sch med, /,
    /kyorin univ fac med, /,
    /kyorin univ hosp, /,
    /kyorin univ sch med, /,
    /kyorin univ, /,
    /kyoritsu womens univ, /,
    /kyoto pharmaceut univ, /,
    /kyoto prefectural univ med, /,
    /kyoto prefectural univ med, grad sch med sci, /,
    /kyoto prefectural univ, /,
    /kyoto tachibana univ, /,
    /kyoto univ arts, /,
    /kyoto univ grad med, dept neurosurg, kyoto 6068507, japan/,
    /kyoto univ grad sch med, /,
    /kyoto univ hlth serv, /,
    /kyoto univ hosp iact, /,
    /kyoto univ hosp, /,
    /kyoto univ, /,
    /kyushu dent univ, /,
    /kyushu kyoritsu univ, /,
    /kyushu univ beppu hosp, /,
    /kyushu univ fukuoka, grad sch informat sci & elect engn, fukuoka, japan/,
    /kyushu univ hosp, /,
    /kyushu univ, /,
    /kyushu womens univ, /,
    /meiji pharmaceut univ, /,
    /meijo univ, /,
    /meikai univ, /,
    /mejiro univ, /,
    /mie univ fac & grad sch med, /,
    /mie univ fac, grad sch med, /,
    /mie univ hosp, /,
    /mie univ, /,
    /mita hosp, int univ hlth & welf, /,
    /miyazaki univ, /,
    /morinomiya univ med sci, /,
    /mukogawa womens univ, /,
    /musashino univ, /,
    /nagaoka univ technol, /,
    /nagaoka univ technol, knowledge min lab, /,
    /nagasaki univ grad, sch biomed sci, /,
    /nagasaki univ hosp int med ctr, /,
    /nagasaki univ hosp, /,
    /nagasaki univ, /,
    /nagoya city univ grad, sch med sci, /,
    /nagoya city univ hosp, /,
    /nagoya city univ west med ctr, /,
    /nagoya city univ, /,
    /nagoya univ arts & sci, sch nutr sci, /,
    /nagoya univ grad sch med, /,
    /nagoya univ hosp, /,
    /nagoya univ, /,
    /nagoya womens univ, /,
    /nakamura gakuen univ, /,
    /nara med univ hosp, /,
    /nara med univ, /,
    /nara univ, /,
    /naragakuen univ, /,
    /narita hosp, /,
    /nihon pharmaceut univ, /,
    /nihon univ hosp, /,
    /nihon univ, /,
    /niigata univ grad sch med & dent sci, /,
    /niigata univ hlth & welf, /,
    /niigata univ med & dent gen hosp, /,
    /niigata univ med & dent hosp, /,
    /niigata univ med & dent hosp, clin & translat res ctr, /,
    /niigata univ med, /,
    /niigata univ pharm & appl life sci, /,
    /niigata univ, /,
    /nippon dent univ, /,
    /notre dame seishin univ, /,
    /ochanomizu univ human dev sci, /,
    /ochanomizu univ, /,
    /oita univ hosp, /,
    /oita univ, /,
    /okayama healthcare profess univ, /,
    /okayama prefectural univ, /,
    /okayama univ fac med, /,
    /okayama univ hosp, /,
    /okayama univ sci, /,
    /okayama univ, /,
    /olta univ, /,
    /open univ japan, /,
    /osaka city univ hosp, /,
    /osaka city univ, /,
    /osaka dent univ, /,
    /osaka med & phamaceut univ, /,
    /osaka med & pharmaceut univ hosp, /,
    /osaka med & pharmaceut univ, /,
    /osaka metropolitan univ grad sch med, /,
    /osaka metropolitan univ hosp, /,
    /osaka metropolitan univ sch med, /,
    /osaka metropolitan univ, /,
    /osaka ohtani univ, /,
    /osaka univ grad sch med, /,
    /osaka univ grad, sch med, suita, osaka, japan/,
    /osaka univ hosp, /,
    /osaka univ, /,
    /otemon gakuin univ, /,
    /otsuma womens univ, /,
    /ritsumeikan univ, /,
    /ryukoku univ, /,
    /saga univ hosp, /,
    /saga univ, /,
    /sagami womens univ, /,
    /saitama med univ ctr, /,
    /saitama med univ hosp, /,
    /saitama med univ int med ctr, /,
    /saitama med univ, /,
    /saitama prefectural univ, /,
    /saitama univ, /,
    /sapporo med univ hosp, /,
    /sapporo med univ med, /,
    /sapporo med univ sch med, /,
    /sapporo med univ, /,
    /seigakuin univ, /,
    /seijoh univ, /,
    /sendai univ, /,
    /setsunan univ, /,
    /shiga med univ, /,
    /shiga univ med sci hosp, /,
    /shiga univ med sci seta tsukinowa, /,
    /shiga univ med sci seta, /,
    /shiga univ med sci, /,
    /shiga univ, /,
    /shijonawate gakuen univ, /,
    /shimane univ hosp, /,
    /shimane univ, /,
    /shinshu univ hosp, /,
    /shinshu univ, /,
    /shinsyu univ hosp, /,
    /shizuoka grad univ publ hlth, /,
    /shizuoka univ, /,
    /shokei gakuin univ, /,
    /show univ, /,
    /showa univ hosp, /,
    /showa univ northern yokohama hosp, /,
    /showa univ, /,
    /shubun univ, /,
    /shukutoku univ, /,
    /sojo univ, /,
    /st lukes int univ lib, /,
    /st lukes int univ, /,
    /st marianna univ hosp, /,
    /st marianna univ sch med hosp, /,
    /st marianna univ sch med, /,
    /st marianna univ sch yokohama city seibu hosp, div metab & endocrinol, /,
    /st marianna univ toyoko hosp, /,
    /st marianna univ, /,
    /sugiyama jogakuen univ, /,
    /suzuka univ med sci, /,
    /takasaki univ hlth & welf, /,
    /teikyo heisei univ, /,
    /teikyo univ hosp mizonokuchi, /,
    /teikyo univ hosp, /,
    /teikyo univ sch med, /,
    /teikyo univ, /,
    /toho univ ohashi, /,
    /toho univ sakura med ctr, /,
    /toho univ, /,
    /tohoku bunka gakuen univ, /,
    /tohoku fukushi univ, /,
    /tohoku med & pharmaceut univ, /,
    /tohoku univ grad sch biomed engn, /,
    /tohoku univ grad sch med, /,
    /tohoku univ grad, /,
    /tohoku univ hosp, /,
    /tohoku univ sch med, /,
    /tohoku univ, /,
    /tohoku university gradua, /,
    /tokai gakuen univ, /,
    /tokai univ hachioji hosp, /,
    /tokai univ hosp, /,
    /tokai univ sch med, /,
    /tokai univ, /,
    /tokoha univ, /,
    /tokushima bunri univ, /,
    /tokushima univ hosp, /,
    /tokushima univ, /,
    /tokuyama univ, /,
    /tokyo denki univ, /,
    /tokyo healthcare univ, /,
    /tokyo jikei kai med univ, /,
    /tokyo med & dent univ hosp med, /,
    /tokyo med & dent univ hosp, /,
    /tokyo med & dent univ tmdu, /,
    /tokyo med & dent univ, /,
    /tokyo med univ hosp, /,
    /tokyo med univ ibaraki med ctr, /,
    /tokyo med univ, /,
    /tokyo univ hosp, /,
    /tokyo univ pharm & life sci/,
    /tokyo univ sci, /,
    /tokyo univ sci, /,
    /tokyo womens med univ hosp, /,
    /tokyo womens med univ med ctr east, /,
    /tokyo womens med univ, /,
    /tottori univ hosp, /,
    /tottori univ, /,
    /toyama univ hosp, /,
    /toyama univ, /,
    /toyo gakuen univ, /,
    /toyohashi sozo univ, /,
    /tsukuba univ hosp, /,
    /tsukuba univ technol, fac hlth sci, /,
    /tsukuba univ, /,
    /tsurumi univ, /,
    /univ ehime, /,
    /univ fukuchiyama, /,
    /univ fukui hosp, /,
    /univ fukui, /,
    /univ grad sch med sci, dept med & biosyst sci, fukuoka, japan/,
    /univ grad sch med, sapporo, hokkaido, japan/,
    /univ human environm, dept psychol sci, matsuyama, ehime, japan/,
    /univ hyogo, /,
    /univ kyushu, /,
    /univ miazakr, fac med, dept neurosurg, div clin neurosci, miyazaki, japan/,
    /univ miyazaki, /,
    /univ nagasaki, /,
    /univ niigata, /,
    /univ occupat & environm hlth hosp, /,
    /univ occupat & environm hlth japan, /,
    /univ occupat & environm hlth, /,
    /univ osaka, mol res ctr childrens mental dev, /,
    /univ ryukyus hosp, /,
    /univ ryukyus, /,
    /univ shizuoka, /,
    /univ tokushima, /,
    /univ tokyo imsut, /,
    /univ tokyo spine grp utsg, tokyo, japan/,
    /univ tokyo, /,
    /univ toyama grad sch med & pharmaceut sci, res ctr idling brain sci, toyama, japan/,
    /univ toyama, /,
    /univ tsukuba hosp, /,
    /univ tsukuba hosp, /,
    /univ tsukuba, /,
    /univ yamanashi hosp, /,
    /univ yamanashi, /,
    /utsunomiya univ, /,
    /wakayama med univ hosp, /,
    /wakayama med univ, /,
    /wakayama univ, /,
    /waseda univ, /,
    /yamagata prefectural univ hlth sci, /,
    /yamagata univ hosp, /,
    /yamagata univ, /,
    /yamaguchi univ grad sch med, /,
    /yamaguchi univ grad, /,
    /yamaguchi univ, /,
    /yamanashi prefectural univ, /,
    /yasuda womens univ, /,
    /yokohama city univ grad sch med, /,
    /yokohama city univ med ctr, /,
    /yokohama city univ med, /,
    /yokohama city univ, /,
    /yokohama natl univ, /,
    /yokomhama city univ, /,
    /tokyo seiei coll/, // 東京聖栄大学
    /fukuoka dent coll/,
    /natl def med coll/, // 防衛医科大学校
    /kawasaki med sch/, // 川崎医科大学
    /okinawa inst sci & technol/, // 沖縄科学技術大学院大学
    /nippon med sch/, // 日本医科大学
    /nippon med coll/,
    /tokyo inst technol/, // 東京工業大学
    /jikei inst, grad sch hlth care sci/, // 滋慶医療科学大学
    /jichi med sch/,
    /toyama coll/, // 富山県立大学
    /saitama med ctr/, // 埼玉医科大学総合医療センター
    /okinawa inst adv sci/, // 沖縄科学技術大学院大学（OIST）
    /tokyo dent coll/,
    /aichi med grad sch/, // 愛知医科大学
    /juntendo tokyo koto geriatr med ctr/, // 順天堂大学医学部附属順天堂東京江東高齢者医療センター
    /kochi med sch/, // 高知大学
    /doshisha womens coll/,
    /st lukes int hosp/, // 聖路加国際病院
    /nagasaki inst appl sci/, // 長崎総合科学大学
    /ichikawa gen hosp/, // 東京歯科大学 市川総合病院
    /hyogo coll med hosp/, // 兵庫医科大学病院
    /japanese red cross coll nursing/, // 日本赤十字看護大学
    /japanese red cross kyushu int coll nursing/,
    /japanese red cross toyota coll nursing/,
    /aizu med ctr/, // 福島県立医科大学 会津医療センター
    /jichi childrens med ctr/, // 自治医科大学 とちぎ子ども医療センター
    /iuhw mita hosp, /, // 国際医療福祉大学三田病院
    /iuhw shioya hosp, /, // 国際医療福祉大学塩谷病院
    /juntendo nerima hosp, /,
    /artificial organ & transplantat div, hepatobiliary pancreat surg div, tokyo, japan/, // 東大病院人工臓器・移植外科
    /daiichi inst technol, /, // 学校法人 都築教育学園 第一工科大学
    /fac med, dept pathol, 7-45-1 nanakuma,jonan ku, fukuoka 8140180, japan/, // 福岡大学医学部病理学
    /fukuoka nursing coll, /, // 福岡看護大学
    /fukushima med coll, /, // 福島県立医科大学
    /grad sch med, dept hlth informat, sakyo ku, yoshida konoe cho, kyoto 6068501, japan/, // 京都大学大学院医学研究科
    /grad sch med, dept radiat oncol & image appl therapy, sakyo ku, kyoto, japan/,
    /grad sch med, tokyo 1138431, japan/, // 順天堂大学附属 順天堂医院
    /grad sch social welf, isesaki, japan/, // 東京福祉大学
    /hlth sci univ, /, // 健康科学大学
    /hyogo coll med, /, // 兵庫医科大学
    /hyogo med coll med, /,
    /immunol frontier res ctr wpi ifrec, lab stat immunol, suita, osaka, japan/, // 大阪大学 免疫学フロンティア研究センター (IFReC)
    /inst glycocore res, grad sch pharmaceut sci, nagoya, japan/,
    /inst stat math, dept data sci, tokyo, japan/, // 大学共同利用機関法人情報・システム研究機構統計数理研究所
    /inst stat math, res ctr med & hlth data sci, tokyo, japan/,
    /inst stat math, tokyo, japan/,
    /kyoto inst technol, grad sch sci & technol, kyoto, japan/, // 京都工芸繊維大学
    /grad sch med, dept emergency & crit care med, chiba, chiba, japan/, // 千葉大学大学院医学研究院・医学部
    /res org informat & syst, database ctr life sci dbcls, chiba, japan/, // 大学共同利用機関法人 情報・システム研究機構 データサイエンス共同利用基盤施設 ライフサイエンス統合データベースセンター
    /13-1 takaramachi, kanazawa 9200934, japan/, // 国立大学法人金沢大学附属病院
    /osaka med coll,/, // 大阪医科薬科大学
    /nihon med sch,/, // 日本医科大学
    /kyoto coll nutr & med sci,/, // 京都栄養医療専門学校
    /global ctr med engn & informat, suita,/, // 大阪大学国際医工情報センター
    /inst human movement & med sci, niigata,/, // 新潟医療福祉大学
    /kawasaki coll allied hlth profess/, // 川崎医療短期大学
    /osaka int ctr inst,/, // 国際医療センター(大阪大学医学部附属病院)
    /1 1 1 minami kogushi, ube, yamaguchi 7558505/, // 山口大学医学部
    /grad sch med, sapporo,/, // 札幌医科大学
    /grad sch med, tokyo,/, // 東京大学大学院医学系研究科
    /2 16 1 sugao miyamae ku, kawasaki/, // 聖マリアンナ医科大学
    /1-1-20 daiko minami,higashi ku, nagoya 4618673,/, // 名古屋大学大学院医学系研究科
    /kagoshima med profess coll,/, // 学校法人原田学園 鹿児島医療技術専門学校
    /res & dev ctr new med frontiers, dept adv med, kitasato, kanagawa,/, // 北里大学医学部附属新世紀医療開発センター
    /dept antibody drug dev, sendai, japan/, // 東北大学大学院医学系研究科・医学部 分子薬理学・抗体創薬研究
    /natl coll nursing, sch nursing, kiyose,/, // 国立看護大学校
    /keio spine res grp ksrg,/, // KSRG(Keio Spine Research Group)
    /tokuyama coll,/, // 徳山工業高等専門学校
    /sch publ hlth, sakyo ku, yoshida konoe cho, kyoto 6068501,/, // 京都大学大学院 医学研究科
    /2-5-1 shikata cho,kita ku, okayama 7008558/, // 岡山大学 鹿田キャンパス
    /natl def acad japan,/, // 防衛大学校
    /natl defense med coll,/, // 防衛医科大学校
    /gen internal med, taihaku ku, ave clin, fukuoka,/, // 福岡大学病院
    /tokyo womens med genet,/, // 東京女子医科大学
    /kyushu inst technol,/, // 九州工業大学
    /hamamatsu oncol ctr,/, // 浜松医科大学医学部附属病院腫瘍センター
    /nagoya inst technol,/, // 名古屋工業大学
    /grad sch educ, dept neuropsychiat, tokyo,/, // 東京大学医学部附属病院 精神神経科
    /grad sch med, ctr res counseling & support serv, tokyo,/, // 東京大学大学院医学系研究科
    /grad sch med, dept cognit & behav sci, tokyo,/, // 東京大学 認知行動科学研究室
    /nitobe bunka coll,/, // 学校法人 新渡戸文化学園 新渡戸文化短期大学
    /saga med sch,/, // 佐賀大学医学部
    /maebashi inst technol,/, // 前橋工科大学
    /tokushima grad sch biomed sci,/, // 徳島大学大学院医歯薬学研究部
    /1-2-3 kasumi,minami ku, hiroshima 7340037,/, // 広島大学薬学部
    /fac med, sapporo, hokkaido, japan/, // 北海道大学大学院医学研究科・医学部産婦人科学教室
  ];
}

module.exports = {
  getUnivNames,
};
